/***************************************************************************
 *   Copyright (C) 2026 by Vadim Peretokin - vadim.peretokin@mudlet.org    *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#include <QtTest/QtTest>

#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QRegularExpression>
#include <QString>
#include <QStringList>

/*
 * src/lua-function-list.json is what the script editor's autocompletion offers: every
 * key is a function name it will insert, every value the argument hint shown with it.
 * The file is generated by CI/update-autocompletion.lua scraping the wiki manual, so
 * the page's own furniture can end up inside a name - which is how all 669 entries came
 * to have "[edit | edit source]" appended, "addAreaName" reading as
 * "addAreaName[edit | edit source]" and pushing the argument hint out of the popup
 * (#10816).
 *
 * Nothing about that breaks the build or the load: the editor simply offers, and
 * inserts, names no script can call. So a name here has to be a plain Lua identifier,
 * and its hint has to be the signature of that same function - a scrape that pairs a
 * heading with the next section's signature is the same defect one column over.
 * Namespaced functions (db:add, table.insert) never reach the file; the generator
 * leaves them out.
 */
class LuaFunctionListTest : public QObject
{
    Q_OBJECT

    // the name the editor would insert: anything else it cannot offer
    static bool offerableName(const QString& name)
    {
        static const QRegularExpression functionName(QStringLiteral("^[A-Za-z_][A-Za-z0-9_]*$"));
        return functionName.match(name).hasMatch();
    }

    // The hint shown beside it: the signature of that function, as text. It has to call
    // this name and not one that merely starts with it - "getAreaRooms1(area id)" is not
    // getAreaRooms' signature, and the file holds enough such near-names for a heading
    // paired with its neighbour's signature to read as a match.
    static bool hintDescribes(const QString& name, const QString& hint)
    {
        if (hint.trimmed().isEmpty() || hint.contains(QLatin1Char('<'))) {
            return false;
        }
        const QRegularExpression call(QStringLiteral("(?<![A-Za-z0-9_])%1\\s*\\(").arg(QRegularExpression::escape(name)));
        return hint.contains(call);
    }

private slots:
    // The two predicates above are what the checks below stand on, and the shipped file
    // is the only input they otherwise ever see - so a predicate that had stopped
    // rejecting anything would look exactly like a clean list.
    void namePredicateRejectsWikiMarkup_data()
    {
        QTest::addColumn<QString>("name");
        QTest::addColumn<bool>("offerable");

        QTest::newRow("a function name") << QStringLiteral("addAreaName") << true;
        QTest::newRow("digits and underscore") << QStringLiteral("cecho2html") << true;
        QTest::newRow("the wiki's section-edit link") << QStringLiteral("addAreaName[edit | edit source]") << false;
        QTest::newRow("a leftover tag") << QStringLiteral("addAreaName</span>") << false;
        QTest::newRow("a section title") << QStringLiteral("Mudlet Object Functions") << false;
        QTest::newRow("a namespaced function") << QStringLiteral("db:add") << false;
        QTest::newRow("a namespaced function with a dot") << QStringLiteral("table.insert") << false;
        QTest::newRow("nothing") << QString() << false;
    }

    void namePredicateRejectsWikiMarkup()
    {
        QFETCH(QString, name);
        QFETCH(bool, offerable);

        QCOMPARE(offerableName(name), offerable);
    }

    void hintPredicateRejectsWrongSignatures_data()
    {
        QTest::addColumn<QString>("name");
        QTest::addColumn<QString>("hint");
        QTest::addColumn<bool>("describes");

        QTest::newRow("its own signature") << QStringLiteral("addAreaName") << QStringLiteral("areaID = addAreaName(areaName)") << true;
        QTest::newRow("another function's signature") << QStringLiteral("sendCmdLine") << QStringLiteral("setConsoleBufferSize([consoleName], linesLimit)") << false;
        QTest::newRow("the signature of a function whose name starts the same") << QStringLiteral("getAreaRooms") << QStringLiteral("getAreaRooms1(area id)") << false;
        QTest::newRow("the signature of a function this one's name starts") << QStringLiteral("cecho") << QStringLiteral("convertedString = cecho2html(str[, resetFormat])") << false;
        QTest::newRow("the name only mentioned, never called") << QStringLiteral("send") << QStringLiteral("see send and sendAll") << false;
        QTest::newRow("MediaWiki's repeated-heading suffix") << QStringLiteral("createMapLabel_2") << QStringLiteral("labelID = createMapLabel(mapLabel)") << false;
        QTest::newRow("markup in the signature") << QStringLiteral("createLabel") << QStringLiteral("<b>labelID</b> = createLabel(name)") << false;
        QTest::newRow("no signature") << QStringLiteral("send") << QString() << false;
        QTest::newRow("only whitespace") << QStringLiteral("send") << QStringLiteral("   ") << false;
    }

    void hintPredicateRejectsWrongSignatures()
    {
        QFETCH(QString, name);
        QFETCH(QString, hint);
        QFETCH(bool, describes);

        QCOMPARE(hintDescribes(name, hint), describes);
    }

    void entriesAreCallableFunctions()
    {
        QFile file(QStringLiteral(MUDLET_SRC_DIR "/lua-function-list.json"));
        QVERIFY2(file.open(QIODevice::ReadOnly | QIODevice::Text), qPrintable(QStringLiteral("cannot read %1").arg(file.fileName())));

        QJsonParseError error;
        const QJsonDocument document = QJsonDocument::fromJson(file.readAll(), &error);
        QVERIFY2(error.error == QJsonParseError::NoError, qPrintable(error.errorString()));
        QVERIFY(document.isObject());
        const QJsonObject functions = document.object();

        // a list that scraped next to nothing would satisfy every check below on its own
        QVERIFY2(functions.size() > 600, qPrintable(QStringLiteral("only %1 functions in the list - the wiki scrape came back short").arg(functions.size())));

        // The manual transcludes a dozen sub-manuals in page order, so a scrape that
        // stopped early keeps its head and loses whole sections off the tail - which a
        // count on its own cannot see. One function per sub-manual, the last of them the
        // last function on the page.
        for (const auto& canary : {"addAreaName",
                                   "addFileWatch",
                                   "addCmdLineSuggestion",
                                   "connectToServer",
                                   "addWordToDictionary",
                                   "spairs",
                                   "openMudletHomeDir",
                                   "debugc",
                                   "ttsClearQueue",
                                   "addCommandLineMenuEvent",
                                   "usingMudletsDiscordID"}) {
            QVERIFY2(functions.contains(QLatin1String(canary)), qPrintable(QStringLiteral("%1 is missing - the wiki scrape lost a whole section of the manual").arg(QLatin1String(canary))));
        }

        QStringList problems;
        for (auto it = functions.constBegin(); it != functions.constEnd(); ++it) {
            const QString hint = it.value().toString();
            if (!offerableName(it.key())) {
                problems.append(QStringLiteral("\"%1\" is not a function name").arg(it.key()));
            }
            if (!hintDescribes(it.key(), hint)) {
                problems.append(QStringLiteral("\"%1\" is shown with \"%2\" rather than its own arguments").arg(it.key(), hint));
            }
        }

        QVERIFY2(problems.isEmpty(),
                 qPrintable(QStringLiteral("the editor cannot offer %1 of the %2 autocompletion entries - regenerate the list with CI/update-autocompletion.lua (first 10):\n%3")
                                    .arg(problems.size())
                                    .arg(functions.size())
                                    .arg(problems.mid(0, 10).join(u'\n'))));
    }
};

QTEST_GUILESS_MAIN(LuaFunctionListTest)

#include "LuaFunctionListTest.moc"
