all: Makefile_TEntityHandlerTest Makefile_TEntityResolverTest Makefile_TLinkStoreTest Makefile_TMxpTagParserTest Makefile_TMxpSendTagHandlerTest
	$(MAKE) -f Makefile_TEntityHandlerTest.Debug
	debug/TEntityHandlerTest
	$(MAKE) -f Makefile_TEntityResolverTest.Debug
	debug/TEntityResolverTest
	$(MAKE) -f Makefile_TLinkStoreTest.Debug
	debug/TLinkStoreTest
	$(MAKE) -f Makefile_TMxpTagParserTest.Debug
	debug/TMxpTagParserTest
	$(MAKE) -f Makefile_TMxpSendTagHandlerTest.Debug
	debug/TMxpSendTagHandlerTest

Makefile_%:
	qmake -o $@ MudletTest.qmake CONFIG+=$@
	
clean:
	del /q .qmake.stash Makefile_*
	rd /s /q debug release
