QT.linuxaccessibility_support_private.VERSION = 5.14.1
QT.linuxaccessibility_support_private.name = QtLinuxAccessibilitySupport
QT.linuxaccessibility_support_private.module = Qt5LinuxAccessibilitySupport
QT.linuxaccessibility_support_private.libs = $$QT_MODULE_LIB_BASE
QT.linuxaccessibility_support_private.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtLinuxAccessibilitySupport $$QT_MODULE_INCLUDE_BASE/QtLinuxAccessibilitySupport/5.14.1 $$QT_MODULE_INCLUDE_BASE/QtLinuxAccessibilitySupport/5.14.1/QtLinuxAccessibilitySupport
QT.linuxaccessibility_support_private.frameworks =
QT.linuxaccessibility_support_private.bins = $$QT_MODULE_BIN_BASE
QT.linuxaccessibility_support_private.depends = core_private dbus gui_private accessibility_support_private
QT.linuxaccessibility_support_private.uses = atspi/nolink
QT.linuxaccessibility_support_private.module_config = v2 staticlib internal_module
QT.linuxaccessibility_support_private.DEFINES = QT_LINUXACCESSIBILITY_SUPPORT_LIB
QT.linuxaccessibility_support_private.enabled_features =
QT.linuxaccessibility_support_private.disabled_features =
QT_CONFIG +=
QT_MODULES += linuxaccessibility_support
