describe("Tests per-room border functions", function()

  local testRoomId

  setup(function()
    -- Create a test area and room
    local areaId = addAreaName("TestBorderArea")
    testRoomId = createRoomID()
    addRoom(testRoomId)
    setRoomArea(testRoomId, areaId)
    setRoomCoordinates(testRoomId, 0, 0, 0)
  end)

  teardown(function()
    -- Clean up test room and area
    deleteRoom(testRoomId)
    deleteArea("TestBorderArea")
  end)

  describe("Tests setRoomBorderColor", function()
    it("should set border color with RGB", function()
      local result = setRoomBorderColor(testRoomId, 255, 0, 0)
      assert.is_true(result)

      local r, g, b, a = getRoomBorderColor(testRoomId)
      assert.are.equal(255, r)
      assert.are.equal(0, g)
      assert.are.equal(0, b)
      assert.are.equal(255, a) -- default alpha
    end)

    it("should set border color with RGBA", function()
      local result = setRoomBorderColor(testRoomId, 0, 255, 0, 128)
      assert.is_true(result)

      local r, g, b, a = getRoomBorderColor(testRoomId)
      assert.are.equal(0, r)
      assert.are.equal(255, g)
      assert.are.equal(0, b)
      assert.are.equal(128, a)
    end)

    it("should return nil for invalid color values", function()
      local result, err = setRoomBorderColor(testRoomId, 256, 0, 0)
      assert.is_nil(result)
      assert.is_string(err)

      result, err = setRoomBorderColor(testRoomId, -1, 0, 0)
      assert.is_nil(result)
      assert.is_string(err)
    end)

    it("should return nil for invalid room ID", function()
      local result, err = setRoomBorderColor(-999, 255, 0, 0)
      assert.is_nil(result)
      assert.is_string(err)
    end)
  end)

  describe("Tests getRoomBorderColor", function()
    it("should return nil when no custom color is set", function()
      clearRoomBorderColor(testRoomId)
      local result = getRoomBorderColor(testRoomId)
      assert.is_nil(result)
    end)
  end)

  describe("Tests clearRoomBorderColor", function()
    it("should clear the border color", function()
      setRoomBorderColor(testRoomId, 255, 0, 0)
      local result = clearRoomBorderColor(testRoomId)
      assert.is_true(result)
      assert.is_nil(getRoomBorderColor(testRoomId))
    end)
  end)

  describe("Tests setRoomBorderThickness", function()
    it("should set valid thickness", function()
      local result = setRoomBorderThickness(testRoomId, 5)
      assert.is_true(result)
      assert.are.equal(5, getRoomBorderThickness(testRoomId))
    end)

    it("should return nil for thickness below 1", function()
      local result, err = setRoomBorderThickness(testRoomId, 0)
      assert.is_nil(result)
      assert.is_string(err)
    end)

    it("should return nil for thickness above 10", function()
      local result, err = setRoomBorderThickness(testRoomId, 11)
      assert.is_nil(result)
      assert.is_string(err)
    end)
  end)

  describe("Tests getRoomBorderThickness", function()
    it("should return nil when using global default", function()
      clearRoomBorderThickness(testRoomId)
      local result = getRoomBorderThickness(testRoomId)
      assert.is_nil(result)
    end)
  end)

  describe("Tests clearRoomBorderThickness", function()
    it("should clear the thickness", function()
      setRoomBorderThickness(testRoomId, 3)
      local result = clearRoomBorderThickness(testRoomId)
      assert.is_true(result)
      assert.is_nil(getRoomBorderThickness(testRoomId))
    end)
  end)

  describe("Tests setRoomBorderStyle", function()
    it("should set dashed style", function()
      local result = setRoomBorderStyle(testRoomId, "dashed")
      assert.is_true(result)
      assert.are.equal("dashed", getRoomBorderStyle(testRoomId))
    end)

    it("should set dotted style", function()
      local result = setRoomBorderStyle(testRoomId, "dotted")
      assert.is_true(result)
      assert.are.equal("dotted", getRoomBorderStyle(testRoomId))
    end)

    it("should accept alternate name 'dash line'", function()
      local result = setRoomBorderStyle(testRoomId, "dash line")
      assert.is_true(result)
      assert.are.equal("dashed", getRoomBorderStyle(testRoomId))
    end)

    it("should set solid style", function()
      local result = setRoomBorderStyle(testRoomId, "solid")
      assert.is_true(result)
      assert.is_nil(getRoomBorderStyle(testRoomId))
    end)

    it("should return nil for invalid style", function()
      local result, err = setRoomBorderStyle(testRoomId, "zigzag")
      assert.is_nil(result)
      assert.is_string(err)
    end)

    it("should return nil for invalid room", function()
      local result, err = setRoomBorderStyle(-999, "dashed")
      assert.is_nil(result)
      assert.is_string(err)
    end)
  end)

  describe("Tests getRoomBorderStyle", function()
    it("should return nil when using default (solid)", function()
      clearRoomBorderStyle(testRoomId)
      local result = getRoomBorderStyle(testRoomId)
      assert.is_nil(result)
    end)
  end)

  describe("Tests clearRoomBorderStyle", function()
    it("should clear the style", function()
      setRoomBorderStyle(testRoomId, "dashed")
      local result = clearRoomBorderStyle(testRoomId)
      assert.is_true(result)
      assert.is_nil(getRoomBorderStyle(testRoomId))
    end)
  end)

end)
