describe("windowVisible", function()
  local runCounter = 0
  local function uniqueName(stem)
    runCounter = runCounter + 1
    return ("%s-%d-%d"):format(stem, os.time(), runCounter)
  end

  it("follows a label as it is hidden and shown", function()
    local name = uniqueName("wvLabel")
    finally(function() deleteLabel(name) end)
    createLabel("main", name, 10, 20, 30, 40, 1)
    assert.is_true(windowVisible(name))
    hideWindow(name)
    assert.is_false(windowVisible(name))
    showWindow(name)
    assert.is_true(windowVisible(name))
  end)

  -- Qt sends a child no event of its own when its parent is hidden or shown
  describe("of a window inside another", function()
    it("follows the scroll box it is in", function()
      local scrollBox, label, console = uniqueName("wvScrollBox"), uniqueName("wvLabel"), uniqueName("wvMiniConsole")
      finally(function() deleteScrollBox(scrollBox) end)
      createScrollBox("main", scrollBox, 10, 20, 300, 300)
      createLabel(scrollBox, label, 5, 6, 40, 20, 1)
      createMiniConsole(scrollBox, console, 7, 8, 200, 100)
      hideWindow(scrollBox)
      assert.are.same({false, false, false}, {windowVisible(scrollBox), windowVisible(label), windowVisible(console)})
      showWindow(scrollBox)
      assert.are.same({true, true, true}, {windowVisible(scrollBox), windowVisible(label), windowVisible(console)})
    end)

    it("follows the user window it is in", function()
      local userWindow, label = uniqueName("wvUserWindow"), uniqueName("wvLabel")
      finally(function()
        deleteLabel(label)
        deleteMiniConsole(userWindow)
      end)
      assert.is_true(openUserWindow(userWindow, false, false, "f"), "the user window did not open")
      createLabel(userWindow, label, 5, 6, 40, 20, 1)
      assert.is_true(windowVisible(label))
      hideWindow(userWindow)
      assert.are.same({false, false}, {windowVisible(userWindow), windowVisible(label)})
      showWindow(userWindow)
      assert.are.same({true, true}, {windowVisible(userWindow), windowVisible(label)})
    end)

    it("stays hidden when it was hidden itself and its parent is shown", function()
      local scrollBox, label = uniqueName("wvScrollBox"), uniqueName("wvLabel")
      finally(function() deleteScrollBox(scrollBox) end)
      createScrollBox("main", scrollBox, 10, 20, 300, 300)
      createLabel(scrollBox, label, 5, 6, 40, 20, 1)
      hideWindow(scrollBox)
      hideWindow(label)
      showWindow(scrollBox)
      assert.is_false(windowVisible(label))
    end)

    it("follows setWindow into a hidden scroll box and back out", function()
      local scrollBox, label, console = uniqueName("wvScrollBox"), uniqueName("wvLabel"), uniqueName("wvMiniConsole")
      finally(function()
        deleteLabel(label)
        deleteMiniConsole(console)
        deleteScrollBox(scrollBox)
      end)
      createScrollBox("main", scrollBox, 10, 20, 300, 300)
      hideWindow(scrollBox)
      createLabel("main", label, 11, 22, 100, 50, 1)
      createMiniConsole("main", console, 10, 20, 200, 100)
      assert.is_true(setWindow(scrollBox, label, 3, 4, true))
      assert.is_true(setWindow(scrollBox, console, 5, 6, true))
      assert.are.same({false, false}, {windowVisible(label), windowVisible(console)})
      assert.is_true(setWindow("main", label, 3, 4, true))
      assert.is_true(setWindow("main", console, 5, 6, true))
      assert.are.same({true, true}, {windowVisible(label), windowVisible(console)})
    end)

    it("follows a scroll box moved by setWindow into a hidden one", function()
      local outer, inner, label = uniqueName("wvOuterScrollBox"), uniqueName("wvInnerScrollBox"), uniqueName("wvLabel")
      finally(function()
        deleteScrollBox(inner)
        deleteScrollBox(outer)
      end)
      createScrollBox("main", outer, 10, 20, 300, 300)
      createScrollBox("main", inner, 10, 20, 200, 200)
      createLabel(inner, label, 5, 6, 40, 20, 1)
      hideWindow(outer)
      assert.is_true(setWindow(outer, inner, 0, 0, true))
      assert.is_false(windowVisible(label))
    end)
  end)

  it("forgets a deleted label", function()
    local name = uniqueName("wvDeletedLabel")
    createLabel("main", name, 10, 20, 30, 40, 1)
    deleteLabel(name)
    assert.is_nil(windowVisible(name))
  end)
end)
