describe("windowVisible", function()
  local runCounter = 0
  local function uniqueName(stem)
    runCounter = runCounter + 1
    return ("%s-%d-%d"):format(stem, os.time(), runCounter)
  end

  it("follows a label as it is hidden and shown", function()
    local name = uniqueName("wvLabel")
    finally(function() deleteLabel(name) end)
    createLabel("main", name, 10, 20, 30, 40, 1)
    assert.is_true(windowVisible(name))
    hideWindow(name)
    assert.is_false(windowVisible(name))
    showWindow(name)
    assert.is_true(windowVisible(name))
  end)

  -- Qt sends a child no ShowToParent or HideToParent of its own when its parent is hidden or shown
  describe("of a window inside another", function()
    it("follows the scroll box it is in", function()
      local scrollBox, label, console = uniqueName("wvScrollBox"), uniqueName("wvLabel"), uniqueName("wvMiniConsole")
      finally(function() deleteScrollBox(scrollBox) end)
      createScrollBox("main", scrollBox, 10, 20, 300, 300)
      createLabel(scrollBox, label, 5, 6, 40, 20, 1)
      createMiniConsole(scrollBox, console, 7, 8, 200, 100)
      hideWindow(scrollBox)
      assert.are.same({false, false, false}, {windowVisible(scrollBox), windowVisible(label), windowVisible(console)})
      showWindow(scrollBox)
      assert.are.same({true, true, true}, {windowVisible(scrollBox), windowVisible(label), windowVisible(console)})
    end)

    it("follows the user window it is in", function()
      local userWindow, label = uniqueName("wvUserWindow"), uniqueName("wvLabel")
      finally(function()
        deleteLabel(label)
        deleteMiniConsole(userWindow)
      end)
      assert.is_true(openUserWindow(userWindow, false, false, "f"), "the user window did not open")
      createLabel(userWindow, label, 5, 6, 40, 20, 1)
      assert.is_true(windowVisible(label))
      hideWindow(userWindow)
      assert.are.same({false, false}, {windowVisible(userWindow), windowVisible(label)})
      showWindow(userWindow)
      assert.are.same({true, true}, {windowVisible(userWindow), windowVisible(label)})
    end)

    it("stays hidden when it was hidden itself and its parent is shown", function()
      local scrollBox, label = uniqueName("wvScrollBox"), uniqueName("wvLabel")
      finally(function() deleteScrollBox(scrollBox) end)
      createScrollBox("main", scrollBox, 10, 20, 300, 300)
      createLabel(scrollBox, label, 5, 6, 40, 20, 1)
      hideWindow(scrollBox)
      hideWindow(label)
      showWindow(scrollBox)
      assert.is_false(windowVisible(label))
    end)

    it("follows setWindow into a hidden scroll box and back out", function()
      local scrollBox, label, console = uniqueName("wvScrollBox"), uniqueName("wvLabel"), uniqueName("wvMiniConsole")
      finally(function()
        deleteLabel(label)
        deleteMiniConsole(console)
        deleteScrollBox(scrollBox)
      end)
      createScrollBox("main", scrollBox, 10, 20, 300, 300)
      hideWindow(scrollBox)
      createLabel("main", label, 11, 22, 100, 50, 1)
      createMiniConsole("main", console, 10, 20, 200, 100)
      assert.is_true(setWindow(scrollBox, label, 3, 4, true))
      assert.is_true(setWindow(scrollBox, console, 5, 6, true))
      assert.are.same({false, false}, {windowVisible(label), windowVisible(console)})
      assert.is_true(setWindow("main", label, 3, 4, true))
      assert.is_true(setWindow("main", console, 5, 6, true))
      assert.are.same({true, true}, {windowVisible(label), windowVisible(console)})
    end)

    -- setParent() hides the widget without telling it
    it("is hidden by setWindow when it is not asked to show", function()
      local scrollBox, label = uniqueName("wvScrollBox"), uniqueName("wvLabel")
      finally(function()
        deleteLabel(label)
        deleteScrollBox(scrollBox)
      end)
      createScrollBox("main", scrollBox, 10, 20, 300, 300)
      createLabel("main", label, 11, 22, 100, 50, 1)
      assert.is_true(setWindow(scrollBox, label, 3, 4, false))
      assert.is_false(windowVisible(label))
    end)

    it("follows a scroll box moved by setWindow into a hidden one", function()
      local outer, inner, label = uniqueName("wvOuterScrollBox"), uniqueName("wvInnerScrollBox"), uniqueName("wvLabel")
      finally(function()
        deleteScrollBox(inner)
        deleteScrollBox(outer)
      end)
      createScrollBox("main", outer, 10, 20, 300, 300)
      createScrollBox("main", inner, 10, 20, 200, 200)
      createLabel(inner, label, 5, 6, 40, 20, 1)
      hideWindow(outer)
      assert.is_true(setWindow(outer, inner, 0, 0, true))
      assert.is_false(windowVisible(label))
    end)

    it("follows a scroll box holding a command line, a text edit and another scroll box", function()
      local outer, inner = uniqueName("wvOuter"), uniqueName("wvInner")
      local cmdLine, textEdit = uniqueName("wvCmdLine"), uniqueName("wvTextEdit")
      finally(function()
        deleteScrollBox(outer)
      end)
      createScrollBox("main", outer, 10, 20, 300, 300)
      createCommandLine(outer, cmdLine, 5, 6, 100, 20)
      createTextEdit(outer, textEdit, 5, 30, 100, 50)
      createScrollBox(outer, inner, 5, 90, 100, 100)
      local function states()
        return {windowVisible(outer), windowVisible(cmdLine), windowVisible(textEdit), windowVisible(inner)}
      end
      hideWindow(outer)
      assert.are.same({false, false, false, false}, states())
      showWindow(outer)
      assert.are.same({true, true, true, true}, states())
    end)

    -- MXP puts a frame's console inside a container and a tab page of its own
    describe("of an MXP frame", function()
      local function openFrame(frame, attributes)
        feedTriggers(('<FRAME Name="%s" %s>'):format(frame, attributes) .. "\n")
      end
      local function closeFrame(frame)
        feedTriggers(('<FRAME %s ACTION="close">'):format(frame) .. "\n")
      end
      local mxpWasForced
      before_each(function()
        mxpWasForced = getConfig("specialForceMXPProcessorOn")
        setConfig("specialForceMXPProcessorOn", true)
      end)
      after_each(function()
        setConfig("specialForceMXPProcessorOn", mxpWasForced)
      end)

      it("is visible once opened", function()
        local frame = uniqueName("wvFrame")
        finally(function() closeFrame(frame) end)
        openFrame(frame, 'Align="right" Width="20%" Height="30%"')
        assert.is_true(windowVisible(frame))
      end)

      it("follows the tab that is showing", function()
        local parent, child = uniqueName("wvTabParent"), uniqueName("wvTabChild")
        finally(function()
          closeFrame(child)
          closeFrame(parent)
        end)
        -- A height in characters keeps the header, and with it the tabs, however small the main window is
        openFrame(parent, 'Align="right" Width="30%" Height="10c" TITLE="Parent"')
        assert.is_true(windowVisible(parent))
        openFrame(child, ('DOCK="%s" Align="client" TITLE="Child"'):format(parent))
        assert.are.same({false, true}, {windowVisible(parent), windowVisible(child)})
        closeFrame(child)
        assert.is_true(windowVisible(parent))
      end)
    end)
  end)

  -- Deleting the scroll box leaves the text edit as all the name means
  it("follows the next window of a name that is released", function()
    local shared = uniqueName("wvShared")
    finally(function() deleteTextEdit(shared) end)
    createScrollBox("main", shared, 10, 20, 120, 90)
    createTextEdit("main", shared, 30, 40, 160, 110)
    hideWindow(shared)
    assert.is_false(windowVisible(shared))
    deleteScrollBox(shared)
    assert.is_true(windowVisible(shared))
  end)

  it("forgets a deleted label", function()
    local name = uniqueName("wvDeletedLabel")
    createLabel("main", name, 10, 20, 30, 40, 1)
    deleteLabel(name)
    assert.is_nil(windowVisible(name))
  end)
end)
