
add_library(Qt5::QWaylandXCompositeEglClientBufferPlugin MODULE IMPORTED)


_populate_WaylandClient_plugin_properties(QWaylandXCompositeEglClientBufferPlugin RELEASE "wayland-graphics-integration-client/libxcomposite-egl.so" FALSE)

list(APPEND Qt5WaylandClient_PLUGINS Qt5::QWaylandXCompositeEglClientBufferPlugin)
set_property(TARGET Qt5::WaylandClient APPEND PROPERTY QT_ALL_PLUGINS_wayland_graphics_integration_client Qt5::QWaylandXCompositeEglClientBufferPlugin)
set_property(TARGET Qt5::QWaylandXCompositeEglClientBufferPlugin PROPERTY QT_PLUGIN_TYPE "wayland-graphics-integration-client")
set_property(TARGET Qt5::QWaylandXCompositeEglClientBufferPlugin PROPERTY QT_PLUGIN_EXTENDS "")
