
add_library(Qt5::QWaylandFullScreenShellV1IntegrationPlugin MODULE IMPORTED)


_populate_WaylandClient_plugin_properties(QWaylandFullScreenShellV1IntegrationPlugin RELEASE "wayland-shell-integration/libfullscreen-shell-v1.so" FALSE)

list(APPEND Qt5WaylandClient_PLUGINS Qt5::QWaylandFullScreenShellV1IntegrationPlugin)
set_property(TARGET Qt5::WaylandClient APPEND PROPERTY QT_ALL_PLUGINS_wayland_shell_integration Qt5::QWaylandFullScreenShellV1IntegrationPlugin)
set_property(TARGET Qt5::QWaylandFullScreenShellV1IntegrationPlugin PROPERTY QT_PLUGIN_TYPE "wayland-shell-integration")
set_property(TARGET Qt5::QWaylandFullScreenShellV1IntegrationPlugin PROPERTY QT_PLUGIN_EXTENDS "")
