
add_library(Qt5::QWaylandXCompositeGlxClientBufferPlugin MODULE IMPORTED)


_populate_WaylandClient_plugin_properties(QWaylandXCompositeGlxClientBufferPlugin RELEASE "wayland-graphics-integration-client/libxcomposite-glx.so" FALSE)

list(APPEND Qt5WaylandClient_PLUGINS Qt5::QWaylandXCompositeGlxClientBufferPlugin)
set_property(TARGET Qt5::WaylandClient APPEND PROPERTY QT_ALL_PLUGINS_wayland_graphics_integration_client Qt5::QWaylandXCompositeGlxClientBufferPlugin)
set_property(TARGET Qt5::QWaylandXCompositeGlxClientBufferPlugin PROPERTY QT_PLUGIN_TYPE "wayland-graphics-integration-client")
set_property(TARGET Qt5::QWaylandXCompositeGlxClientBufferPlugin PROPERTY QT_PLUGIN_EXTENDS "")
