#!/bin/sh

if [ ! -d $HOME/.config/mudlet ] ; then
	mkdir -p $HOME/.config/mudlet
	cp /usr/share/mudlet/LuaGlobal.lua $HOME/.config/mudlet
	cp /usr/share/mudlet/mudlet_documentation.html $HOME/.config/mudlet
fi

cd /usr/share/mudlet
./mudlet
