name: Build Mudlet in Github Actions CI
on: 
  - pull_request
  - push

jobs:
  compile-mudlet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: development
        submodules: true
        fetch-depth: 0

    - name: 'Run CMake with Ninja'
      uses: lukka/run-cmake@v0
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ runner.workspace }}/b//unixmakefiles'
        cmakeAppendedArgs: '-G "Ninja" '
