name: 🔨 Build Mudlet (windows)
on:
  push:
    branches: [master, development, release-*]
    tags: [Mudlet-*]
  pull_request:
  workflow_dispatch:
    inputs:
      scheduled:
        description: 'Imitate a scheduled build'
        required: false
        default: 'false'
  schedule:
    - cron: '0 2 * * *'

jobs:
  compile-mudlet:
    name: ${{matrix.buildname}}
    runs-on: ${{matrix.os}}
    if: github.repository_owner == 'Mudlet'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            buildname: 'windows64'

    steps:
    - name: Checkout Mudlet source code
      uses: actions/checkout@v5
      with:
        submodules: true
        fetch-depth: 0

    - name: (Windows) Setup MSYS2
      if: matrix.buildname == 'windows64'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true

    - name: (Windows) Build Environment Setup
      shell: msys2 {0}
      env:
        # Used to flag a "release" build - when a Git "tagged" commit is pushed
        GITHUB_REPO_TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        $GITHUB_WORKSPACE/CI/setup-windows-sdk.sh
        $GITHUB_WORKSPACE/CI/validate-deployment-for-windows.sh

    - name: Restore ccache
      id: restore-ccache
      uses: actions/cache/restore@v4
      with:
        path: ${{runner.workspace}}/ccache
        key: ccache-${{matrix.os}}-${{matrix.buildname}}-${{ github.sha }}
        restore-keys: ccache-${{matrix.os}}-${{matrix.buildname}}

    - name: (Windows) Build
      shell: msys2 {0}
      env:
        GITHUB_REPO_NAME: ${{ github.repository }}
        GITHUB_REPO_TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        GITHUB_SCHEDULED_BUILD: ${{ github.event_name == 'schedule' || github.event.inputs.scheduled == 'true' }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        # This should export the following to the GitHub "environment" for later
        # steps:
        # ABORT_WORKFLOW - Only created by PublicTest builds when it is not
        #   required; needed because there still isn't a way to abort a workflow
        #   without it showing up as an error. See:
        #   https://github.com/orgs/community/discussions/82744
        # BUILD_ACTION - what this build is doing, one of:
        #   "Release" - a tagged release branch representing that release version of Mudlet
        #   "PublicTest" - the nightly build (if needed) of the development branch
        #   "PullRequest" - a commit to a PR
        #   "Testing" - when a PR is merged into the "development" branch
        #   "Archive" - all other cases, just produces a zip file of everything needed to run the build
        # BUILD_COMMIT - the identifier of where in the Git history this build is
        # BUILD_CONFIG - whether to produce an optimised or a debuggable build
        #   "release" - default, currently only value that can be used, will be set to this if not previously defined
        #   "debug" - not yet supported, but intended to include extra debug information and be built for debugging
        # MUDLET_VERSION_BUILD - something that identifies the build
        # MAKE_PORTABLE - if 'true' then also produce a "portable" version
        #   approprate to the BUILD_CONFIG. Normally this would be the case for
        #   "Release" and "PublicTest" but during development/debugging of this
        #   it may also include the "PullRequest" ones.
        # VERSION - the x.y.z (only) part of the Mudlet version number, without any suffix
      run: |
        export -p
        $GITHUB_WORKSPACE/CI/build-mudlet-for-windows.sh

    - name: (Windows) Run Lua tests
      if: env.ABORT_WORKFLOW != 'true'
      timeout-minutes: 5
      shell: msys2 {0}
      env:
        AUTORUN_BUSTED_TESTS: 'true'
        TESTS_DIRECTORY: ${{github.workspace}}/src/mudlet-lua/tests
        QUIT_MUDLET_AFTER_TESTS: 'true'
      run: |
        LUA_PATH=$(cygpath -u "$(luarocks --lua-version 5.1 path --lr-path)" )
        export LUA_PATH
        LUA_CPATH=$(cygpath -u "$(luarocks --lua-version 5.1 path --lr-cpath)" )
        export LUA_CPATH
        $GITHUB_WORKSPACE/build-$MSYSTEM/release/mudlet.exe --profile "Mudlet self-test"

    - name: Check that Lua tests were passed
      shell: msys2 {0}
      if: env.ABORT_WORKFLOW != 'true'
      run: |
        if [ -e $TEMP/busted-tests-failed ]
        then
          echo "Lua tests failed - see the action called 'Run Lua tests' above for detailed output."
          exit 1
        fi

    - name: Save ccache
      if: env.ABORT_WORKFLOW != 'true' && steps.restore-ccache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{runner.workspace}}/ccache
        key: ${{ steps.restore-ccache.outputs.cache-primary-key }}

    - name: (Windows) Package
      if: env.ABORT_WORKFLOW != 'true'
      shell: msys2 {0}
      env:
        BUILD_ACTION: ${{ env.BUILD_ACTION }}
        BUILD_COMMIT: ${{ env.BUILD_COMMIT }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        MUDLET_VERSION_BUILD: ${{ env.MUDLET_VERSION_BUILD }}
      run: |
        export -p
        $GITHUB_WORKSPACE/CI/package-mudlet-for-windows.sh

    - name: (Windows) Login to Azure
      uses: azure/login@v2
      if: env.ABORT_WORKFLOW != 'true' && github.actor != 'dependabot[bot]' && (github.event_name == 'push' || github.event_name == 'schedule' || github.event.inputs.scheduled == 'true' || github.event.pull_request.head.repo.full_name == github.repository)
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Azure access token for code signing
      shell: pwsh
      if: env.ABORT_WORKFLOW != 'true' && github.actor != 'dependabot[bot]' && (github.event_name == 'push' || github.event_name == 'schedule' || github.event.inputs.scheduled == 'true' || github.event.pull_request.head.repo.full_name == github.repository)
      run: |
        $token = (az account get-access-token --resource https://codesigning.azure.net | ConvertFrom-Json).accessToken
        "::add-mask::$token"
        "AZURE_ACCESS_TOKEN=$token" | Add-Content -Path $env:GITHUB_ENV

    - name: (Windows) Deploy
      if: env.ABORT_WORKFLOW != 'true'
      shell: msys2 {0}
      env:
        AZURE_ACCESS_TOKEN: ${{ env.AZURE_ACCESS_TOKEN }}
        BUILD_ACTION: ${{ env.BUILD_ACTION }}
        BUILD_COMMIT: ${{ env.BUILD_COMMIT }}
        DBLSQD_PASS: ${{secrets.DBLSQD_PASS}}
        DBLSQD_USER: ${{secrets.DBLSQD_USER}}
        DEPLOY_KEY_PASS: ${{secrets.DEPLOY_KEY_PASS}}
        DEPLOY_PATH: ${{secrets.DEPLOY_PATH}}
        DEPLOY_SSH_KEY: ${{secrets.UPLOAD_PRIVATEKEY}}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPO_NAME: ${{ github.repository }}
        GITHUB_REPO_TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        MAKE_PORTABLE: ${{ env.MAKE_PORTABLE }}
        MUDLET_VERSION_BUILD: ${{ env.MUDLET_VERSION_BUILD }}
        X_WP_DOWNLOAD_TOKEN: ${{secrets.X_WP_DOWNLOAD_TOKEN}}
      run: |
        export -p
        $GITHUB_WORKSPACE/CI/deploy-mudlet-for-windows.sh

    - name: Create portable artifact for uploading
      uses: actions/upload-artifact@v4
      if: env.MAKE_PORTABLE == 'true' && env.PORTABLE_ARTIFACT_NAME
      with:
        name: ${{env.PORTABLE_ARTIFACT_NAME}}
        path: ${{env.PORTABLE_ARTIFACT_WINPATHORFILE}}
        # As this is a single self-extracting archive file another round of
        # compression is pointless!
        compression-level: 0
        if-no-files-found: ignore

    - name: Create intermediate artifact for debugging
      uses: actions/upload-artifact@v5
      if: env.INTERMEDIATE_ARTIFACT_NAME
      with:
        name: ${{env.INTERMEDIATE_ARTIFACT_NAME}}
        path: ${{env.INTERMEDIATE_ARTIFACT_WINPATHORFILE}}
        # Maximumal compression to minimise space needed:
        compression-level: 9
        if-no-files-found: ignore

    - name: Create main artifact for uploading
      # Uploads the zipped contents of ARTIFACT_WINPATHORFILE as an "artifact"
      # with the above name - the Environmental variables are created by the
      # deploy-mudlet-for-windows.sh script:
      uses: actions/upload-artifact@v5
      if: env.ARTIFACT_NAME
      with:
        # The name presented in the "artifacts" listing for the (zip) file created
        name: ${{env.ARTIFACT_NAME}}
        # One (or more if the "path: |" is used) to a path to a directory - or a
        # (possibly wildcarded) file name to identify what to include in the
        # archive - if a directory all files in and below that directory are
        # included (except for hidden files unless:
        # include-hidden-files: true
        # is specified:
        path: ${{env.ARTIFACT_WINPATHORFILE}}
        compression-level: ${{env.ARTIFACT_COMPRESSION}}

    - name: Upload main artifact to make.mudlet.org
      if: env.ARTIFACT_NAME
      shell: msys2 {0}
      # Depending on the type (see BUILD_ACTION) of workflow this may or may not
      # need unzipping once it gets to our own website:
      run: curl --retry 5 -X POST "https://make.mudlet.org/snapshots/gha_queue.php?artifact_name=${{env.ARTIFACT_NAME}}&unzip=${{env.ARTIFACT_UNZIP}}"

    - name: Upload portable artifact to make.mudlet.org
      if: env.MAKE_PORTABLE == 'true' && env.PORTABLE_ARTIFACT_NAME
      shell: msys2 {0}
      # The artifact creation process zipped (well "stored", as there is no
      # compression) the self-extracting archive which does need "unzipping" but
      # only to get the archive file back once we've uploaded it:
      run: curl --retry 5 -X POST "https://make.mudlet.org/snapshots/gha_queue.php?artifact_name=${{env.PORTABLE_ARTIFACT_NAME}}&unzip=1"

    - name: Register PTB Release
      shell: msys2 {0}
      if: env.ABORT_WORKFLOW != 'true' && (github.event_name == 'schedule' || github.event.inputs.scheduled == 'true')
      env:
        BUILD_COMMIT: ${{ env.BUILD_COMMIT }}
        VERSION_STRING: ${{ env.VERSION_STRING }}
      run: $GITHUB_WORKSPACE/CI/register-windows-release.sh
