name: 🔨 Build Mudlet Windows
on:
  push:
    branches: [medievia-bash]
    tags: [Mudlet-*]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  msys2-mingw32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          #install: git mingw-w64-i686-gcc
      - name: Echo environment information
        run: |
          echo "MSYS2 installation path: $MSYSTEM_PREFIX"
          echo "Home directory: $HOME"
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "Runner temp directory: $RUNNER_TEMP"
          echo "Current PATH: $PATH"
      - name: Make scripts executable
        run: |
          chmod +x $GITHUB_WORKSPACE/CI/setup-windows-sdk.sh
          chmod +x $GITHUB_WORKSPACE/CI/build-mudlet-for-windows.sh
      - name: Mudlet Build Environment Setup
        run: |
          export PATH="/c/Program Files/Git/bin:$PATH"
          $GITHUB_WORKSPACE/CI/setup-windows-sdk.sh base
      - name: Mudlet Build
        run: |
          export BUILD_CONFIG=release
          $GITHUB_WORKSPACE/CI/build-mudlet-for-windows.sh
      - name: Package Mudlet
        run: |
          export BUILD_CONFIG=release
          $GITHUB_WORKSPACE/CI/package-mudlet-for-windows.sh

