name: Run Busted out-of-client testsa github action to

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v2

    - name: install busted
      run: |
        luarocks install busted

    - name: run tests
      run: |
        busted -o utfTerminal src/mudlet-lua/tests
